"""LLM Settings module for hierarchical LLM configuration.

Provides org → team → user hierarchy for LLM provider and model settings,
including support for custom OpenAI-compatible endpoints.
"""

from backend.llm_settings.models import (
    BUILT_IN_MODELS,
    CustomLLMProvider,
    CustomLLMProviderCreate,
    CustomLLMProviderPublic,
    CustomLLMProviderUpdate,
    EffectiveLLMSettings,
    LLMProvider,
    LLMSettingsBase,
    ModelCapability,
    ModelInfo,
    OrganizationLLMSettings,
    OrganizationLLMSettingsPublic,
    OrganizationLLMSettingsUpdate,
    ProviderApiKeyUpdate,
    ProviderStatusResponse,
    TeamLLMSettings,
    TeamLLMSettingsPublic,
    TeamLLMSettingsUpdate,
    UserLLMSettings,
    UserLLMSettingsPublic,
    UserLLMSettingsUpdate,
)
from backend.llm_settings.service import (
    create_custom_provider,
    delete_custom_provider,
    get_available_models,
    get_custom_provider,
    get_custom_provider_api_key,
    get_effective_llm_settings,
    get_model_for_chat,
    get_or_create_org_llm_settings,
    get_or_create_team_llm_settings,
    get_or_create_user_llm_settings,
    has_custom_provider_api_key,
    list_custom_providers,
    test_custom_provider_connection,
    update_custom_provider,
    update_org_llm_settings,
    update_team_llm_settings,
    update_user_llm_settings,
)

__all__ = [
    # Models
    "BUILT_IN_MODELS",
    "CustomLLMProvider",
    "CustomLLMProviderCreate",
    "CustomLLMProviderPublic",
    "CustomLLMProviderUpdate",
    "EffectiveLLMSettings",
    "LLMProvider",
    "LLMSettingsBase",
    "ModelCapability",
    "ModelInfo",
    "OrganizationLLMSettings",
    "OrganizationLLMSettingsPublic",
    "OrganizationLLMSettingsUpdate",
    "ProviderApiKeyUpdate",
    "ProviderStatusResponse",
    "TeamLLMSettings",
    "TeamLLMSettingsPublic",
    "TeamLLMSettingsUpdate",
    "UserLLMSettings",
    "UserLLMSettingsPublic",
    "UserLLMSettingsUpdate",
    # Service functions
    "create_custom_provider",
    "delete_custom_provider",
    "get_available_models",
    "get_custom_provider",
    "get_custom_provider_api_key",
    "get_effective_llm_settings",
    "get_model_for_chat",
    "get_or_create_org_llm_settings",
    "get_or_create_team_llm_settings",
    "get_or_create_user_llm_settings",
    "has_custom_provider_api_key",
    "list_custom_providers",
    "test_custom_provider_connection",
    "update_custom_provider",
    "update_org_llm_settings",
    "update_team_llm_settings",
    "update_user_llm_settings",
]
