"""initial_schema

Revision ID: 0ebb995494ae
Revises:

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ebb995494ae"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create required PostgreSQL extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("logger", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message_en", sa.Text(), nullable=True),
        sa.Column("message_localized", sa.Text(), nullable=True),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("module", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("function", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("exception_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("exception_message", sa.Text(), nullable=True),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_app_logs_level_time", "app_logs", ["level", "timestamp"], unique=False
    )
    op.create_index(
        "idx_app_logs_org_time",
        "app_logs",
        ["organization_id", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_app_logs_level"), "app_logs", ["level"], unique=False)
    op.create_index(
        op.f("ix_app_logs_organization_id"),
        "app_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_app_logs_timestamp"), "app_logs", ["timestamp"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "action_message_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "action_message_localized",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "actor_ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("actor_user_agent", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("targets", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_logs_action_time",
        "audit_logs",
        ["action", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_audit_logs_actor_time",
        "audit_logs",
        ["actor_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_audit_logs_org_time",
        "audit_logs",
        ["organization_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"),
        "audit_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_team_id"), "audit_logs", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False
    )
    op.create_table(
        "encrypted_secrets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "encrypted_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_encrypted_secrets_path"), "encrypted_secrets", ["path"], unique=True
    )
    op.create_table(
        "organization",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column(
            "logo_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_name"), "organization", ["name"], unique=False
    )
    op.create_index(op.f("ix_organization_slug"), "organization", ["slug"], unique=True)
    op.create_table(
        "revoked_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("jti", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_revoked_tokens_jti"), "revoked_tokens", ["jti"], unique=True
    )
    op.create_index(
        op.f("ix_revoked_tokens_user_id"), "revoked_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "profile_image_url",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("password_changed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_guardrails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("guardrails_enabled", sa.Boolean(), nullable=False),
        sa.Column("input_blocked_keywords", sa.JSON(), nullable=False),
        sa.Column("input_blocked_patterns", sa.JSON(), nullable=False),
        sa.Column(
            "input_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("output_blocked_keywords", sa.JSON(), nullable=False),
        sa.Column("output_blocked_patterns", sa.JSON(), nullable=False),
        sa.Column(
            "output_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("pii_detection_enabled", sa.Boolean(), nullable=False),
        sa.Column("pii_types", sa.JSON(), nullable=False),
        sa.Column(
            "pii_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("allow_team_override", sa.Boolean(), nullable=False),
        sa.Column("allow_user_override", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_guardrails_organization_id"),
        "organization_guardrails",
        ["organization_id"],
        unique=True,
    )
    op.create_table(
        "organization_llm_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "default_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("default_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "default_model_display_name",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("default_temperature", sa.Float(), nullable=False),
        sa.Column("default_max_tokens", sa.Integer(), nullable=True),
        sa.Column("default_top_p", sa.Float(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("fallback_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "fallback_models", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("allow_team_customization", sa.Boolean(), nullable=False),
        sa.Column("allow_user_customization", sa.Boolean(), nullable=False),
        sa.Column("allow_per_request_model_selection", sa.Boolean(), nullable=False),
        sa.Column(
            "enabled_providers", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "disabled_models", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id"),
    )
    op.create_table(
        "organization_member",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "MEMBER", name="orgrole"), nullable=False
        ),
        sa.Column("team_order", sa.JSON(), nullable=True),
        sa.Column("sidebar_preferences", sa.JSON(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_org_member_org_user"
        ),
    )
    op.create_index(
        "ix_org_member_org_role",
        "organization_member",
        ["organization_id", "role"],
        unique=False,
    )
    op.create_index(
        "ix_org_member_user", "organization_member", ["user_id"], unique=False
    )
    op.create_table(
        "organization_rag_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rag_enabled", sa.Boolean(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("chunks_per_query", sa.Integer(), nullable=False),
        sa.Column("similarity_threshold", sa.Float(), nullable=False),
        sa.Column("use_hybrid_search", sa.Boolean(), nullable=False),
        sa.Column("reranking_enabled", sa.Boolean(), nullable=False),
        sa.Column("query_rewriting_enabled", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("rag_customization_enabled", sa.Boolean(), nullable=False),
        sa.Column("allow_team_customization", sa.Boolean(), nullable=False),
        sa.Column("allow_user_customization", sa.Boolean(), nullable=False),
        sa.Column("max_documents_per_user", sa.Integer(), nullable=False),
        sa.Column("max_document_size_mb", sa.Integer(), nullable=False),
        sa.Column("max_total_storage_gb", sa.Integer(), nullable=False),
        sa.Column(
            "allowed_file_types", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id"),
    )
    op.create_table(
        "organization_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_enabled", sa.Boolean(), nullable=False),
        sa.Column("chat_panel_enabled", sa.Boolean(), nullable=False),
        sa.Column("memory_enabled", sa.Boolean(), nullable=False),
        sa.Column("mcp_enabled", sa.Boolean(), nullable=False),
        sa.Column("mcp_tool_approval_required", sa.Boolean(), nullable=False),
        sa.Column(
            "disabled_mcp_servers",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "disabled_tools", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("mcp_allow_custom_servers", sa.Boolean(), nullable=False),
        sa.Column("mcp_max_servers_per_team", sa.Integer(), nullable=False),
        sa.Column("mcp_max_servers_per_user", sa.Integer(), nullable=False),
        sa.Column("max_media_file_size_mb", sa.Integer(), nullable=False),
        sa.Column("max_media_per_message", sa.Integer(), nullable=False),
        sa.Column("max_media_storage_mb", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id"),
    )
    op.create_table(
        "organization_theme_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "default_theme_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "default_light_theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "default_dark_theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "custom_light_theme", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "custom_dark_theme", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("theme_customization_enabled", sa.Boolean(), nullable=False),
        sa.Column("allow_team_customization", sa.Boolean(), nullable=False),
        sa.Column("allow_user_customization", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id"),
    )
    op.create_table(
        "team",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column(
            "logo_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_name"), "team", ["name"], unique=False)
    op.create_index(
        op.f("ix_team_organization_id"), "team", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_team_slug"), "team", ["slug"], unique=False)
    op.create_table(
        "user_guardrails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("guardrails_enabled", sa.Boolean(), nullable=False),
        sa.Column("input_blocked_keywords", sa.JSON(), nullable=False),
        sa.Column("input_blocked_patterns", sa.JSON(), nullable=False),
        sa.Column(
            "input_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("output_blocked_keywords", sa.JSON(), nullable=False),
        sa.Column("output_blocked_patterns", sa.JSON(), nullable=False),
        sa.Column(
            "output_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("pii_detection_enabled", sa.Boolean(), nullable=False),
        sa.Column("pii_types", sa.JSON(), nullable=False),
        sa.Column(
            "pii_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_guardrails_user_id"), "user_guardrails", ["user_id"], unique=True
    )
    op.create_table(
        "user_llm_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "preferred_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("preferred_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("preferred_temperature", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_rag_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rag_enabled", sa.Boolean(), nullable=False),
        sa.Column("chunks_per_query", sa.Integer(), nullable=False),
        sa.Column("similarity_threshold", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_enabled", sa.Boolean(), nullable=False),
        sa.Column("chat_panel_enabled", sa.Boolean(), nullable=False),
        sa.Column("memory_enabled", sa.Boolean(), nullable=False),
        sa.Column("mcp_enabled", sa.Boolean(), nullable=False),
        sa.Column("mcp_tool_approval_required", sa.Boolean(), nullable=False),
        sa.Column(
            "disabled_mcp_servers",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "disabled_tools", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_theme_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("theme_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("light_theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dark_theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "custom_light_theme", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "custom_dark_theme", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "chat_media",
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "mime_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_media_created_by", "chat_media", ["created_by_id"], unique=False
    )
    op.create_index(
        "idx_chat_media_org_team_user",
        "chat_media",
        ["organization_id", "team_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_media_deleted_at"), "chat_media", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_chat_media_filename"), "chat_media", ["filename"], unique=False
    )
    op.create_table(
        "conversation",
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("is_starred", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_deleted_at"), "conversation", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_organization_id"),
        "conversation",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_conversation_team_deleted",
        "conversation",
        ["team_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_team_id"), "conversation", ["team_id"], unique=False
    )
    op.create_index(
        "ix_conversation_team_user_updated",
        "conversation",
        ["team_id", "created_by_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "custom_llm_provider",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("provider_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "base_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column(
            "available_models", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custom_llm_provider_organization_id"),
        "custom_llm_provider",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_llm_provider_team_id"),
        "custom_llm_provider",
        ["team_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "file_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "mime_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "processing_status",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_documents_org_team_user",
        "documents",
        ["organization_id", "team_id", "user_id"],
        unique=False,
    )
    op.create_index(
        "idx_documents_status", "documents", ["processing_status"], unique=False
    )
    op.create_index(
        op.f("ix_documents_deleted_at"), "documents", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_documents_filename"), "documents", ["filename"], unique=False
    )
    op.create_index(
        op.f("ix_documents_processing_status"),
        "documents",
        ["processing_status"],
        unique=False,
    )
    op.create_table(
        "invitation",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("invited_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("org_role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACCEPTED", "EXPIRED", "REVOKED", name="invitationstatus"
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["invited_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitation_email"), "invitation", ["email"], unique=False)
    op.create_index(
        op.f("ix_invitation_token_hash"), "invitation", ["token_hash"], unique=True
    )
    op.create_table(
        "mcp_server",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("transport", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("auth_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "auth_header_name",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column(
            "auth_secret_ref",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("tool_prefix", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "prompt_type",
            sa.Enum("TEMPLATE", "SYSTEM", name="prompttype"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_is_active"), "prompt", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_prompt_organization_id"), "prompt", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_prompt_team_id"), "prompt", ["team_id"], unique=False)
    op.create_index(op.f("ix_prompt_user_id"), "prompt", ["user_id"], unique=False)
    op.create_table(
        "team_guardrails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("guardrails_enabled", sa.Boolean(), nullable=False),
        sa.Column("input_blocked_keywords", sa.JSON(), nullable=False),
        sa.Column("input_blocked_patterns", sa.JSON(), nullable=False),
        sa.Column(
            "input_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("output_blocked_keywords", sa.JSON(), nullable=False),
        sa.Column("output_blocked_patterns", sa.JSON(), nullable=False),
        sa.Column(
            "output_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("pii_detection_enabled", sa.Boolean(), nullable=False),
        sa.Column("pii_types", sa.JSON(), nullable=False),
        sa.Column(
            "pii_action",
            sa.Enum("BLOCK", "WARN", "REDACT", name="guardrailaction"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_guardrails_team_id"), "team_guardrails", ["team_id"], unique=True
    )
    op.create_table(
        "team_llm_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "default_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("default_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("default_temperature", sa.Float(), nullable=True),
        sa.Column("default_max_tokens", sa.Integer(), nullable=True),
        sa.Column("allow_user_customization", sa.Boolean(), nullable=False),
        sa.Column(
            "disabled_models", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id"),
    )
    op.create_table(
        "team_member",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MEMBER", "VIEWER", name="teamrole"),
            nullable=False,
        ),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("org_member_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_member_id"], ["organization_member.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "org_member_id", name="uq_team_member_team_org_member"
        ),
    )
    op.create_table(
        "team_rag_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rag_enabled", sa.Boolean(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("chunks_per_query", sa.Integer(), nullable=False),
        sa.Column("similarity_threshold", sa.Float(), nullable=False),
        sa.Column("use_hybrid_search", sa.Boolean(), nullable=False),
        sa.Column("reranking_enabled", sa.Boolean(), nullable=False),
        sa.Column("query_rewriting_enabled", sa.Boolean(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("rag_customization_enabled", sa.Boolean(), nullable=False),
        sa.Column("allow_user_customization", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id"),
    )
    op.create_table(
        "team_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_enabled", sa.Boolean(), nullable=False),
        sa.Column("chat_panel_enabled", sa.Boolean(), nullable=False),
        sa.Column("memory_enabled", sa.Boolean(), nullable=False),
        sa.Column("mcp_enabled", sa.Boolean(), nullable=False),
        sa.Column("mcp_tool_approval_required", sa.Boolean(), nullable=False),
        sa.Column(
            "disabled_mcp_servers",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "disabled_tools", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("mcp_allow_custom_servers", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id"),
    )
    op.create_table(
        "team_theme_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "default_theme_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "default_light_theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "default_dark_theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "custom_light_theme", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "custom_dark_theme", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("theme_customization_enabled", sa.Boolean(), nullable=False),
        sa.Column("allow_user_customization", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id"),
    )
    op.create_table(
        "conversation_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("sources_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("media_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("guardrail_blocked", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversation.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conv_msg_conv_created",
        "conversation_message",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_message_conversation_id"),
        "conversation_message",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_message_created_by_id"),
        "conversation_message",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_message_deleted_at"),
        "conversation_message",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_message_organization_id"),
        "conversation_message",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_message_team_id"),
        "conversation_message",
        ["team_id"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        # EMBEDDING_DIMENSION: 1536 is the standard dimension for text-embedding-3-small
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True  # noqa: PLR2004
        ),
        sa.Column("metadata_", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chunks_document", "document_chunks", ["document_id"], unique=False
    )
    op.create_index(
        "idx_chunks_tenant",
        "document_chunks",
        ["organization_id", "team_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"),
        "document_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_organization_id"),
        "document_chunks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_team_id"), "document_chunks", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_user_id"), "document_chunks", ["user_id"], unique=False
    )

    # Create HNSW vector index for RAG semantic search (requires pgvector extension)
    op.execute("""
        CREATE INDEX idx_document_chunks_embedding_hnsw
        ON document_chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    # Create GIN index for full-text search on conversation message content
    op.execute("""
        CREATE INDEX idx_conversation_message_content_trgm
        ON conversation_message
        USING gin (content gin_trgm_ops)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop custom indexes first
    op.execute("DROP INDEX IF EXISTS idx_conversation_message_content_trgm")
    op.execute("DROP INDEX IF EXISTS idx_document_chunks_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_chunks_user_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_team_id"), table_name="document_chunks")
    op.drop_index(
        op.f("ix_document_chunks_organization_id"), table_name="document_chunks"
    )
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index("idx_chunks_tenant", table_name="document_chunks")
    op.drop_index("idx_chunks_document", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(
        op.f("ix_conversation_message_team_id"), table_name="conversation_message"
    )
    op.drop_index(
        op.f("ix_conversation_message_organization_id"),
        table_name="conversation_message",
    )
    op.drop_index(
        op.f("ix_conversation_message_deleted_at"), table_name="conversation_message"
    )
    op.drop_index(
        op.f("ix_conversation_message_created_by_id"), table_name="conversation_message"
    )
    op.drop_index(
        op.f("ix_conversation_message_conversation_id"),
        table_name="conversation_message",
    )
    op.drop_index("ix_conv_msg_conv_created", table_name="conversation_message")
    op.drop_table("conversation_message")
    op.drop_table("team_theme_settings")
    op.drop_table("team_settings")
    op.drop_table("team_rag_settings")
    op.drop_table("team_member")
    op.drop_table("team_llm_settings")
    op.drop_index(op.f("ix_team_guardrails_team_id"), table_name="team_guardrails")
    op.drop_table("team_guardrails")
    op.drop_index(op.f("ix_prompt_user_id"), table_name="prompt")
    op.drop_index(op.f("ix_prompt_team_id"), table_name="prompt")
    op.drop_index(op.f("ix_prompt_organization_id"), table_name="prompt")
    op.drop_index(op.f("ix_prompt_is_active"), table_name="prompt")
    op.drop_table("prompt")
    op.drop_table("mcp_server")
    op.drop_index(op.f("ix_invitation_token_hash"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_email"), table_name="invitation")
    op.drop_table("invitation")
    op.drop_index(op.f("ix_documents_processing_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_filename"), table_name="documents")
    op.drop_index(op.f("ix_documents_deleted_at"), table_name="documents")
    op.drop_index("idx_documents_status", table_name="documents")
    op.drop_index("idx_documents_org_team_user", table_name="documents")
    op.drop_table("documents")
    op.drop_index(
        op.f("ix_custom_llm_provider_team_id"), table_name="custom_llm_provider"
    )
    op.drop_index(
        op.f("ix_custom_llm_provider_organization_id"), table_name="custom_llm_provider"
    )
    op.drop_table("custom_llm_provider")
    op.drop_index("ix_conversation_team_user_updated", table_name="conversation")
    op.drop_index(op.f("ix_conversation_team_id"), table_name="conversation")
    op.drop_index("ix_conversation_team_deleted", table_name="conversation")
    op.drop_index(op.f("ix_conversation_organization_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_deleted_at"), table_name="conversation")
    op.drop_table("conversation")
    op.drop_index(op.f("ix_chat_media_filename"), table_name="chat_media")
    op.drop_index(op.f("ix_chat_media_deleted_at"), table_name="chat_media")
    op.drop_index("idx_chat_media_org_team_user", table_name="chat_media")
    op.drop_index("idx_chat_media_created_by", table_name="chat_media")
    op.drop_table("chat_media")
    op.drop_table("user_theme_settings")
    op.drop_table("user_settings")
    op.drop_table("user_rag_settings")
    op.drop_table("user_llm_settings")
    op.drop_index(op.f("ix_user_guardrails_user_id"), table_name="user_guardrails")
    op.drop_table("user_guardrails")
    op.drop_index(op.f("ix_team_slug"), table_name="team")
    op.drop_index(op.f("ix_team_organization_id"), table_name="team")
    op.drop_index(op.f("ix_team_name"), table_name="team")
    op.drop_table("team")
    op.drop_table("organization_theme_settings")
    op.drop_table("organization_settings")
    op.drop_table("organization_rag_settings")
    op.drop_index("ix_org_member_user", table_name="organization_member")
    op.drop_index("ix_org_member_org_role", table_name="organization_member")
    op.drop_table("organization_member")
    op.drop_table("organization_llm_settings")
    op.drop_index(
        op.f("ix_organization_guardrails_organization_id"),
        table_name="organization_guardrails",
    )
    op.drop_table("organization_guardrails")
    op.drop_table("item")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_revoked_tokens_user_id"), table_name="revoked_tokens")
    op.drop_index(op.f("ix_revoked_tokens_jti"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    op.drop_index(op.f("ix_organization_slug"), table_name="organization")
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_table("organization")
    op.drop_index(op.f("ix_encrypted_secrets_path"), table_name="encrypted_secrets")
    op.drop_table("encrypted_secrets")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_team_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("idx_audit_logs_org_time", table_name="audit_logs")
    op.drop_index("idx_audit_logs_actor_time", table_name="audit_logs")
    op.drop_index("idx_audit_logs_action_time", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_app_logs_timestamp"), table_name="app_logs")
    op.drop_index(op.f("ix_app_logs_organization_id"), table_name="app_logs")
    op.drop_index(op.f("ix_app_logs_level"), table_name="app_logs")
    op.drop_index("idx_app_logs_org_time", table_name="app_logs")
    op.drop_index("idx_app_logs_level_time", table_name="app_logs")
    op.drop_table("app_logs")
    # ### end Alembic commands ###

    # Drop PostgreSQL extensions (optional - may want to keep these)
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS vector")
