from backend.auth.crud import (
    authenticate,
    create_user,
    get_user_by_email,
    get_user_by_id,
    update_user,
)
from backend.auth.deps import (
    CurrentUser,
    SessionDep,
    TokenDep,
    get_current_user,
)
from backend.auth.models import (
    AdminPasswordResetRequest,
    Message,
    NewPassword,
    PasswordResetRequest,
    PasswordResetWithTokenRequest,
    RefreshTokenRequest,
    ResendVerificationRequest,
    SendVerificationCodeRequest,
    Token,
    TokenPayload,
    UpdatePassword,
    UpdateSignupEmailRequest,
    User,
    UserCreate,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
    VerificationStatusResponse,
    VerifyEmailRequest,
)
from backend.auth.token_revocation import (
    RevokedToken,
    cleanup_expired_tokens,
    is_token_revoked,
    load_revoked_tokens_to_cache,
    revoke_all_user_tokens,
    revoke_token,
)
from backend.core.db import get_db

__all__ = [
    # Verification schemas
    "AdminPasswordResetRequest",
    "CurrentUser",
    "Message",
    "NewPassword",
    "PasswordResetRequest",
    "PasswordResetWithTokenRequest",
    "RefreshTokenRequest",
    "ResendVerificationRequest",
    "RevokedToken",
    "SendVerificationCodeRequest",
    # Dependencies
    "SessionDep",
    "Token",
    "TokenDep",
    "TokenPayload",
    "UpdatePassword",
    "UpdateSignupEmailRequest",
    # Models
    "User",
    "UserCreate",
    "UserPublic",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UsersPublic",
    "VerificationStatusResponse",
    "VerifyEmailRequest",
    # CRUD
    "authenticate",
    "cleanup_expired_tokens",
    "create_user",
    "get_current_user",
    "get_db",
    "get_user_by_email",
    "get_user_by_id",
    "is_token_revoked",
    "load_revoked_tokens_to_cache",
    "revoke_all_user_tokens",
    "revoke_token",
    "update_user",
]
