/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsPromptsRouteImport } from './routes/settings.prompts'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as OrgSettingsRouteImport } from './routes/org/settings'
import { Route as OrgPromptsRouteImport } from './routes/org/prompts'
import { Route as OrgApiKeysRouteImport } from './routes/org/api-keys'
import { Route as OrgSettingsIndexRouteImport } from './routes/org/settings.index'
import { Route as TeamTeamIdSearchRouteImport } from './routes/team.$teamId.search'
import { Route as TeamTeamIdChatRouteImport } from './routes/team.$teamId.chat'
import { Route as OrgSettingsSectionRouteImport } from './routes/org/settings.$section'
import { Route as OrgTeamTeamIdSettingsRouteImport } from './routes/org/team/$teamId.settings'
import { Route as OrgTeamTeamIdPromptsRouteImport } from './routes/org/team/$teamId.prompts'
import { Route as OrgTeamTeamIdDocumentsRouteImport } from './routes/org/team/$teamId.documents'
import { Route as OrgTeamTeamIdApiKeysRouteImport } from './routes/org/team/$teamId.api-keys'
import { Route as OrgTeamTeamIdSettingsIndexRouteImport } from './routes/org/team/$teamId.settings.index'
import { Route as OrgTeamTeamIdSettingsSectionRouteImport } from './routes/org/team/$teamId.settings.$section'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPromptsRoute = SettingsPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgPromptsRoute = OrgPromptsRouteImport.update({
  id: '/org/prompts',
  path: '/org/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgApiKeysRoute = OrgApiKeysRouteImport.update({
  id: '/org/api-keys',
  path: '/org/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSettingsIndexRoute = OrgSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSettingsRoute,
} as any)
const TeamTeamIdSearchRoute = TeamTeamIdSearchRouteImport.update({
  id: '/team/$teamId/search',
  path: '/team/$teamId/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdChatRoute = TeamTeamIdChatRouteImport.update({
  id: '/team/$teamId/chat',
  path: '/team/$teamId/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSettingsSectionRoute = OrgSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => OrgSettingsRoute,
} as any)
const OrgTeamTeamIdSettingsRoute = OrgTeamTeamIdSettingsRouteImport.update({
  id: '/org/team/$teamId/settings',
  path: '/org/team/$teamId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamTeamIdPromptsRoute = OrgTeamTeamIdPromptsRouteImport.update({
  id: '/org/team/$teamId/prompts',
  path: '/org/team/$teamId/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamTeamIdDocumentsRoute = OrgTeamTeamIdDocumentsRouteImport.update({
  id: '/org/team/$teamId/documents',
  path: '/org/team/$teamId/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamTeamIdApiKeysRoute = OrgTeamTeamIdApiKeysRouteImport.update({
  id: '/org/team/$teamId/api-keys',
  path: '/org/team/$teamId/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamTeamIdSettingsIndexRoute =
  OrgTeamTeamIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgTeamTeamIdSettingsRoute,
  } as any)
const OrgTeamTeamIdSettingsSectionRoute =
  OrgTeamTeamIdSettingsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => OrgTeamTeamIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/org/api-keys': typeof OrgApiKeysRoute
  '/org/prompts': typeof OrgPromptsRoute
  '/org/settings': typeof OrgSettingsRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/': typeof SettingsIndexRoute
  '/org/settings/$section': typeof OrgSettingsSectionRoute
  '/team/$teamId/chat': typeof TeamTeamIdChatRoute
  '/team/$teamId/search': typeof TeamTeamIdSearchRoute
  '/org/settings/': typeof OrgSettingsIndexRoute
  '/org/team/$teamId/api-keys': typeof OrgTeamTeamIdApiKeysRoute
  '/org/team/$teamId/documents': typeof OrgTeamTeamIdDocumentsRoute
  '/org/team/$teamId/prompts': typeof OrgTeamTeamIdPromptsRoute
  '/org/team/$teamId/settings': typeof OrgTeamTeamIdSettingsRouteWithChildren
  '/org/team/$teamId/settings/$section': typeof OrgTeamTeamIdSettingsSectionRoute
  '/org/team/$teamId/settings/': typeof OrgTeamTeamIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/org/api-keys': typeof OrgApiKeysRoute
  '/org/prompts': typeof OrgPromptsRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings': typeof SettingsIndexRoute
  '/org/settings/$section': typeof OrgSettingsSectionRoute
  '/team/$teamId/chat': typeof TeamTeamIdChatRoute
  '/team/$teamId/search': typeof TeamTeamIdSearchRoute
  '/org/settings': typeof OrgSettingsIndexRoute
  '/org/team/$teamId/api-keys': typeof OrgTeamTeamIdApiKeysRoute
  '/org/team/$teamId/documents': typeof OrgTeamTeamIdDocumentsRoute
  '/org/team/$teamId/prompts': typeof OrgTeamTeamIdPromptsRoute
  '/org/team/$teamId/settings/$section': typeof OrgTeamTeamIdSettingsSectionRoute
  '/org/team/$teamId/settings': typeof OrgTeamTeamIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/org/api-keys': typeof OrgApiKeysRoute
  '/org/prompts': typeof OrgPromptsRoute
  '/org/settings': typeof OrgSettingsRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/': typeof SettingsIndexRoute
  '/org/settings/$section': typeof OrgSettingsSectionRoute
  '/team/$teamId/chat': typeof TeamTeamIdChatRoute
  '/team/$teamId/search': typeof TeamTeamIdSearchRoute
  '/org/settings/': typeof OrgSettingsIndexRoute
  '/org/team/$teamId/api-keys': typeof OrgTeamTeamIdApiKeysRoute
  '/org/team/$teamId/documents': typeof OrgTeamTeamIdDocumentsRoute
  '/org/team/$teamId/prompts': typeof OrgTeamTeamIdPromptsRoute
  '/org/team/$teamId/settings': typeof OrgTeamTeamIdSettingsRouteWithChildren
  '/org/team/$teamId/settings/$section': typeof OrgTeamTeamIdSettingsSectionRoute
  '/org/team/$teamId/settings/': typeof OrgTeamTeamIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/organizations'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/signup'
    | '/org/api-keys'
    | '/org/prompts'
    | '/org/settings'
    | '/settings/$section'
    | '/settings/prompts'
    | '/settings/'
    | '/org/settings/$section'
    | '/team/$teamId/chat'
    | '/team/$teamId/search'
    | '/org/settings/'
    | '/org/team/$teamId/api-keys'
    | '/org/team/$teamId/documents'
    | '/org/team/$teamId/prompts'
    | '/org/team/$teamId/settings'
    | '/org/team/$teamId/settings/$section'
    | '/org/team/$teamId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/organizations'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/org/api-keys'
    | '/org/prompts'
    | '/settings/$section'
    | '/settings/prompts'
    | '/settings'
    | '/org/settings/$section'
    | '/team/$teamId/chat'
    | '/team/$teamId/search'
    | '/org/settings'
    | '/org/team/$teamId/api-keys'
    | '/org/team/$teamId/documents'
    | '/org/team/$teamId/prompts'
    | '/org/team/$teamId/settings/$section'
    | '/org/team/$teamId/settings'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/organizations'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/signup'
    | '/org/api-keys'
    | '/org/prompts'
    | '/org/settings'
    | '/settings/$section'
    | '/settings/prompts'
    | '/settings/'
    | '/org/settings/$section'
    | '/team/$teamId/chat'
    | '/team/$teamId/search'
    | '/org/settings/'
    | '/org/team/$teamId/api-keys'
    | '/org/team/$teamId/documents'
    | '/org/team/$teamId/prompts'
    | '/org/team/$teamId/settings'
    | '/org/team/$teamId/settings/$section'
    | '/org/team/$teamId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  OrgApiKeysRoute: typeof OrgApiKeysRoute
  OrgPromptsRoute: typeof OrgPromptsRoute
  OrgSettingsRoute: typeof OrgSettingsRouteWithChildren
  TeamTeamIdChatRoute: typeof TeamTeamIdChatRoute
  TeamTeamIdSearchRoute: typeof TeamTeamIdSearchRoute
  OrgTeamTeamIdApiKeysRoute: typeof OrgTeamTeamIdApiKeysRoute
  OrgTeamTeamIdDocumentsRoute: typeof OrgTeamTeamIdDocumentsRoute
  OrgTeamTeamIdPromptsRoute: typeof OrgTeamTeamIdPromptsRoute
  OrgTeamTeamIdSettingsRoute: typeof OrgTeamTeamIdSettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/prompts': {
      id: '/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof SettingsPromptsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/org/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/prompts': {
      id: '/org/prompts'
      path: '/org/prompts'
      fullPath: '/org/prompts'
      preLoaderRoute: typeof OrgPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/api-keys': {
      id: '/org/api-keys'
      path: '/org/api-keys'
      fullPath: '/org/api-keys'
      preLoaderRoute: typeof OrgApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/settings/': {
      id: '/org/settings/'
      path: '/'
      fullPath: '/org/settings/'
      preLoaderRoute: typeof OrgSettingsIndexRouteImport
      parentRoute: typeof OrgSettingsRoute
    }
    '/team/$teamId/search': {
      id: '/team/$teamId/search'
      path: '/team/$teamId/search'
      fullPath: '/team/$teamId/search'
      preLoaderRoute: typeof TeamTeamIdSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/chat': {
      id: '/team/$teamId/chat'
      path: '/team/$teamId/chat'
      fullPath: '/team/$teamId/chat'
      preLoaderRoute: typeof TeamTeamIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/settings/$section': {
      id: '/org/settings/$section'
      path: '/$section'
      fullPath: '/org/settings/$section'
      preLoaderRoute: typeof OrgSettingsSectionRouteImport
      parentRoute: typeof OrgSettingsRoute
    }
    '/org/team/$teamId/settings': {
      id: '/org/team/$teamId/settings'
      path: '/org/team/$teamId/settings'
      fullPath: '/org/team/$teamId/settings'
      preLoaderRoute: typeof OrgTeamTeamIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/team/$teamId/prompts': {
      id: '/org/team/$teamId/prompts'
      path: '/org/team/$teamId/prompts'
      fullPath: '/org/team/$teamId/prompts'
      preLoaderRoute: typeof OrgTeamTeamIdPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/team/$teamId/documents': {
      id: '/org/team/$teamId/documents'
      path: '/org/team/$teamId/documents'
      fullPath: '/org/team/$teamId/documents'
      preLoaderRoute: typeof OrgTeamTeamIdDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/team/$teamId/api-keys': {
      id: '/org/team/$teamId/api-keys'
      path: '/org/team/$teamId/api-keys'
      fullPath: '/org/team/$teamId/api-keys'
      preLoaderRoute: typeof OrgTeamTeamIdApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/team/$teamId/settings/': {
      id: '/org/team/$teamId/settings/'
      path: '/'
      fullPath: '/org/team/$teamId/settings/'
      preLoaderRoute: typeof OrgTeamTeamIdSettingsIndexRouteImport
      parentRoute: typeof OrgTeamTeamIdSettingsRoute
    }
    '/org/team/$teamId/settings/$section': {
      id: '/org/team/$teamId/settings/$section'
      path: '/$section'
      fullPath: '/org/team/$teamId/settings/$section'
      preLoaderRoute: typeof OrgTeamTeamIdSettingsSectionRouteImport
      parentRoute: typeof OrgTeamTeamIdSettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsPromptsRoute: typeof SettingsPromptsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsPromptsRoute: SettingsPromptsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface OrgSettingsRouteChildren {
  OrgSettingsSectionRoute: typeof OrgSettingsSectionRoute
  OrgSettingsIndexRoute: typeof OrgSettingsIndexRoute
}

const OrgSettingsRouteChildren: OrgSettingsRouteChildren = {
  OrgSettingsSectionRoute: OrgSettingsSectionRoute,
  OrgSettingsIndexRoute: OrgSettingsIndexRoute,
}

const OrgSettingsRouteWithChildren = OrgSettingsRoute._addFileChildren(
  OrgSettingsRouteChildren,
)

interface OrgTeamTeamIdSettingsRouteChildren {
  OrgTeamTeamIdSettingsSectionRoute: typeof OrgTeamTeamIdSettingsSectionRoute
  OrgTeamTeamIdSettingsIndexRoute: typeof OrgTeamTeamIdSettingsIndexRoute
}

const OrgTeamTeamIdSettingsRouteChildren: OrgTeamTeamIdSettingsRouteChildren = {
  OrgTeamTeamIdSettingsSectionRoute: OrgTeamTeamIdSettingsSectionRoute,
  OrgTeamTeamIdSettingsIndexRoute: OrgTeamTeamIdSettingsIndexRoute,
}

const OrgTeamTeamIdSettingsRouteWithChildren =
  OrgTeamTeamIdSettingsRoute._addFileChildren(
    OrgTeamTeamIdSettingsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  OrgApiKeysRoute: OrgApiKeysRoute,
  OrgPromptsRoute: OrgPromptsRoute,
  OrgSettingsRoute: OrgSettingsRouteWithChildren,
  TeamTeamIdChatRoute: TeamTeamIdChatRoute,
  TeamTeamIdSearchRoute: TeamTeamIdSearchRoute,
  OrgTeamTeamIdApiKeysRoute: OrgTeamTeamIdApiKeysRoute,
  OrgTeamTeamIdDocumentsRoute: OrgTeamTeamIdDocumentsRoute,
  OrgTeamTeamIdPromptsRoute: OrgTeamTeamIdPromptsRoute,
  OrgTeamTeamIdSettingsRoute: OrgTeamTeamIdSettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
